project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/",include('shopping.urls',namespace='axf')),
    url(r"^api/shopping/v1/",include('shopping.urls_apis_v1',namespace='api/shopping/v1')),
]

shopping/urls.py
from django.conf.urls import url
from .views import *
urlpatterns=[
    url(r'^home$',home,name='home'),
    url(r'^cart$',cart,name='cart'),
    url(r'^market$',market,name='market'),
    url(r'^mine$',mine,name='mine'),
    url(r"^register$",register_view,name='register'),
    url(r"^login$",login_view,name='login'),
    url(r"^logout$",logout_api,name='logout'),
    url(r"^market_with_params/(?P<type_id>\d+)/(?P<sub_type_id>\d+)/(?P<sort>\d+)$",market_with_params,name='market_with_params'),
    url(r"^order$",order_view,name='order')
]

shopping/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .choices import ORDER_STATUS
# Create your models here.
class MyUser(AbstractUser):
    icon = models.ImageField(
        upload_to='icon',
        verbose_name='头像'
    )

class Address(models.Model):
    detail = models.CharField(
        max_length=255,
        verbose_name='详细地址'
    )
    is_delete = models.BooleanField(
        default=False
    )
    is_default = models.BooleanField(
        default=True,
    )
    user = models.ForeignKey(
        MyUser,
        null=True
    )
    class Meta:
        unique_together = ['user','is_default']
        index_together = ['user','is_default']

class BaseData(models.Model):
    img = models.CharField(
        max_length=255
    )
    name = models.CharField(
        max_length=60
    )
    trackid = models.CharField(
        max_length=60
    )

    class Meta:
        abstract=True

class Wheel(BaseData):
    class Meta:
        db_table = 'axf_wheel'

class Nav(BaseData):
    class Meta:
        db_table = 'axf_nav'

class MustBuy(BaseData):
    class Meta:
        db_table = 'axf_mustbuy'

class Shop(BaseData):
    class Meta:
        db_table = 'axf_shop'


class MainShow(BaseData):
    categoryid = models.CharField(
        max_length=255
    )
    brandname = models.CharField(
        max_length=255
    )
    img1 = models.CharField(
        max_length=255
    )
    childcid1 = models.CharField(
        max_length=255
    )
    productid1 = models.CharField(
        max_length=255
    )
    longname1 = models.CharField(
        max_length=255
    )
    price1 = models.CharField(
        max_length=255
    )
    marketprice1 = models.CharField(
        max_length=255
    )

    img2 = models.CharField(
        max_length=255
    )
    childcid2 = models.CharField(
        max_length=255
    )
    productid2 = models.CharField(
        max_length=255
    )
    longname2 = models.CharField(
        max_length=255
    )
    price2 = models.CharField(
        max_length=255
    )
    marketprice2 = models.CharField(
        max_length=255
    )

    img3 = models.CharField(
        max_length=255
    )
    childcid3 = models.CharField(
        max_length=255
    )
    productid3 = models.CharField(
        max_length=255
    )
    longname3 = models.CharField(
        max_length=255
    )
    price3 = models.CharField(
        max_length=255
    )
    marketprice3 = models.CharField(
        max_length=255
    )

class Goods(models.Model):
    productid = models.CharField(
        max_length=20
    )
    productimg = models.CharField(
        max_length=200
    )
    productname = models.CharField(
        max_length=200,
        null=True
    )
    productlongname = models.CharField(
        max_length=200
    )
    isxf = models.BooleanField(
        default=0
    )
    pmdesc = models.BooleanField(
        default=0
    )
    specifics = models.CharField(
        max_length=20
    )
    price = models.FloatField()
    marketprice = models.FloatField()
    categoryid = models.IntegerField()
    childcid = models.IntegerField()
    childcidname = models.CharField(
        max_length=10
    )
    dealerid = models.CharField(
        max_length=20
    )
    storenums = models.IntegerField()
    productnum = models.IntegerField()

    def __str__(self):
        return str(self.price)

    class Meta:
        db_table = "axf_goods"


class Cart(models.Model):
    user = models.ForeignKey(
        MyUser,
        db_index=True
    )

    goods = models.ForeignKey(
        Goods
    )

    num = models.IntegerField(
        '购买的商品数量'
    )
    is_select = models.BooleanField(
        default=True
    )
    create_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name='创建时间'
    )

    update_time = models.DateTimeField(
        auto_now=True,
        verbose_name='更新时间'
    )

class GoodsTypes(models.Model):
    typeid = models.CharField(
        max_length=40
    )

    typename = models.CharField(
        max_length=50
    )
    childtypenames= models.CharField(
        max_length=255
    )
    typesort = models.IntegerField( )

    class Meta:
        db_table = 'axf_foodtypes'

class ErrorLog(models.Model):
    msg = models.CharField(
        max_length=255,
        verbose_name="错误信息"
    )
    api_path = models.CharField(
        max_length=255,
        verbose_name="请求路径"
    )
    date = models.DateField(
        auto_now_add=True,
        verbose_name="错误发送时间"
    )

class Order(models.Model):
    user = models.ForeignKey(
        MyUser
    )
    number = models.CharField(
        '订单号',
        max_length=50,
    )
    status = models.IntegerField(
        choices= ORDER_STATUS,
        default=1
    )
    create_time = models.DateTimeField(
        '生成的时间',
        auto_now_add=True
    )
    address = models.ForeignKey(
        Address
    )

class OrderItem(models.Model):
    order = models.ForeignKey(
        Order
    )
    goods_num = models.IntegerField(
        '商品数量',
    )
    goods = models.ForeignKey(
        Goods
    )
    price = models.FloatField()
    desc = models.CharField(
        max_length=255,
        null=True
    )

shopping/views.py
from __future__ import unicode_literals
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .tasks import send_my_mail
from .models import *
from .util import *
from .serializers import OrderItemSerializer
# Create your views here.
def home(request):
    tops = Wheel.objects.all()
    navs = Nav.objects.all()
    mustbuys = MustBuy.objects.all()
    shops = Shop.objects.all()
    infos =MainShow.objects.all()
    data = {
        'title':'首页',
        'tops':tops,
        'navs':navs,
        'mustbuys':mustbuys,
        'shop_0':shops.first(),
        'shop_1_3':shops[1:3],
        'shop_4_7':shops[3:7],
        'shop_7_11':shops[7:],
        'infos':infos

    }
    return render(request,'home/home.html',data)

def market_with_params(req,type_id,sub_type_id,sort):
    types = GoodsTypes.objects.all()
    goods = Goods.objects.filter(categoryid=type_id)

    goods_type = types.get(typeid=type_id)

    sub_types = goods_type.childtypenames.split("#")
    sub_type_datas = []
    for i in sub_types:
        sub_type_datas.append(i.split(":"))
    # 如果点击的不是全部分类，再进行二级分类
    if sub_type_id !='0':
        goods = goods.filter(childcid=sub_type_id)
    if sort == '1':
        goods = goods.order_by('price')
    elif sort == '2':
        goods = goods.order_by('-productnum')
    else:
        pass
    if req.user.is_authenticated:
        if hasattr(req.user,'cart_set'):
            # cart_set反向查询
            cart_data = req.user.cart_set.all()
            for good in goods:
                cart_goods = cart_data.filter(goods=good)
                if cart_goods.exists():
                    good.cart_num = cart_goods.first().num

    data ={
        'title':'闪购',
        'types':types,
        'select_type_id':type_id,
        'goods':goods,
        'sub_type_datas':sub_type_datas,
        'select_sub_type_id':sub_type_id,
        'current_sort':sort
    }
    return render(req,'market/market.html',data)

def market(request):
    # types = GoodsTypes.objects.all()
    # data ={
    #     'title':'闪购',
    #     'types':types
    # }
    return redirect(reverse('axf:market_with_params',kwargs={'type_id':104749,'sub_type_id':0,'sort':0}))

@login_required(login_url='/axf/login')
def cart(request):
    user = request.user
    cartitems = Cart.objects.filter(user_id=user.id)
    is_select_all = True
    if cartitems.filter(is_select=False).exists():
        is_select_all = False
    money = get_sum_money(cartitems)
    print(is_select_all)
    data ={
        'title':'购物车',
        'cartitems':cartitems,
        'is_select_all':is_select_all,
        'money':'%.2f'%money,
        'user':user
    }
    return render(request,'cart/cart.html',data)

def mine(request):
    user = request.user
    # is_login = False
    # uname = ''
    # icon = ''
    #
    # if user.is_authenticated:
    #     is_login=True
    #     uname = user.username
    #     icon = user.icon
    is_login,name,icon = (True,user.username,user.icon) if user.is_authenticated else (False,'','')
    data ={
        'title':'我的',
        'is_login':is_login,
        'name':name,
        'icon':"http://{url}/static/uploads/{icon}".format(url=request.get_host(),icon=icon)
    }
    return render(request,'mine/mine.html',data)

def logout_api(req):
    logout(req)
    return redirect(reverse('axf:mine'))



def register_view(req):
    return render(req, 'user/register.html')

def login_view(req):
    return render(req,'user/login.html')

@login_required(login_url='/axf/login')
def order_view(request):
    user = request.user
    address = Address.objects.get(user_id=user.id,is_default=True)
    order = Order.objects.create(
        user_id=user.id,
        number= get_order_number(),
        address=address
    )
    cart_items = Cart.objects.select_related('goods').filter(
        user_id=user.id,
        is_select=True
    )

    # 判断选中商品是否存在
    if not cart_items.exists():
        raise Exception("您未选中任何商品")
    order_items = [ ]
    for i in cart_items:
        # 判断库存
        desc = None
        if i.num > i.goods.storenums:
            desc = '当前库存不足，请稍后购买'
        order_item = OrderItem.objects.create(
            order_id=order.id,
            goods_num=i.num,
            goods_id=i.goods_id,
            price=i.goods.price,
            desc=desc,
        )
        order_items.append(order_item)
    sum_money = get_sum_money(cart_items)
    cart_items.delete()
    data = {
        'sum_money':sum_money,
        'order_items':OrderItemSerializer(order_items,many=True).data,
        'order_number':order.number
    }
    return render(request,'order/order.html',data)

shopping/templates/cart/cart.html
{% extends 'base/base_main.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/cart/cart.css' %}">
{% endblock %}

{% block content %}
    <div id="cart">
        <h3>{{ title }}</h3>
        <div class="full">
            <section>
                <ul>
                    <li>收货人:{{ user.username }}    <div><p>修改》</p></div></li>
                    <li>电话:{{ user.phone }}</li>
                    <li>收货地址:{{ user.address }}</li>
                </ul>
                <div class="bill">
                    <p>闪送超市</p>
                    <p>满100减99</p>
                    <a href="">凑单专区</a>
                </div>
                <div class="delivery">
                    <span>收货时间</span>
                    <span>一小时送达</span>
                    <a href="">可预订</a>
                </div>
                <div class="delivery">
                    <span>收货备注</span>
                    <input type="text" placeholder="如有其它需要，请留言">
                </div>
                <menu>
                    <ul>
                        {% for i in cartitems %}
                            <li class="menuList" cart_id="{{ i.id }}">
                                <div class="confirm">
                                    <span>
                                        {% if i.is_select %}
                                            <span>
                                            √
                                            </span>
                                        {% else %}
                                            <span></span>
                                        {% endif %}
                                    </span>
                                </div>
                                <a href="">
                                    <img src="{{ i.goods.productimg }}" alt="">
                                    <p>{{ i.goods.productlongname }}</p>
                                    <p>{{ i.goods.price }}</p>
                                </a>
                            <section>
                                <button class="subCart">-</button>
                                <span>{{ i.num }}</span>
                                <button class="addCart">+</button>
                            </section>
                            </li>
                        {% endfor %}

                    </ul>
                </menu>
                <div class="payTheBill">
                    <div class="all_select">
                        <span>
                            {% if is_select_all %}
                                <span>√</span>
                            {% else %}
                                <span></span>
                            {% endif %}

                        </span>
                    </div>
                    <p>
                        <span>全选</span>
                        <span>共计</span>
                        <span id="sum_money">{{ money }}</span>
                    </p>

                    <span>
                            <a href="{% url 'axf:order' %}">下单</a>
                    </span>
                </div>
            </section>
        </div>

    </div>
{% endblock %}

{% block js %}
{{ block.super }}
    <script src="{% static 'axf/cart/js/cart.js' %}"></script>
{% endblock %}